import * as React from 'react'
import { Link, useNavigate, useRouter, useRouterState } from '@tanstack/react-router'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import {
  BookMarked,
  Building2,
  ChevronsUpDown,
  History,
  LayoutDashboard,
  LogOut,
  Menu as MenuIcon,
  Moon,
  Network,
  Plus,
  ScrollText,
  Search,
  ShieldCheck,
  Sparkles,
  Sun,
  UserRound,
  X,
} from 'lucide-react'
import { api, ApiError } from '~/lib/api'
import { canCreateInWorkspace } from '~/lib/policy'
import { workspaceNameProblem } from '~/lib/account'
import type { Me } from '~/lib/types'
import { Logo } from './logo'
import { useTheme } from './theme'
import { CommandPalette, type PaletteLink } from './command'
import { useToast } from './toast'
import { Avatar, Badge, Button, Callout, Dialog, Field, Input, Kbd, Menu, MenuItem, MenuLabel, MenuSeparator, Tip, buttonClass, cn } from './ui'

type NavTo = '/' | '/library' | '/runs' | '/access' | '/audit' | '/system-design'
type NavItem = { to: NavTo; label: string; icon: React.ReactNode; exact?: boolean; adminOnly?: boolean }
type NavGroup = { label: string; items: NavItem[] }

export const NAV: NavGroup[] = [
  {
    label: 'Workspace',
    items: [
      { to: '/', label: 'Dashboard', icon: <LayoutDashboard />, exact: true },
      { to: '/library', label: 'Recipe library', icon: <BookMarked /> },
      { to: '/runs', label: 'My runs', icon: <History /> },
    ],
  },
  {
    label: 'Governance',
    items: [
      { to: '/access', label: 'Access', icon: <ShieldCheck /> },
      { to: '/audit', label: 'Audit log', icon: <ScrollText />, adminOnly: true },
      { to: '/system-design', label: 'System design', icon: <Network /> },
    ],
  },
]

const ROLE_TONE = { admin: 'brand', member: 'flow', viewer: 'neutral' } as const

function useSignOut() {
  const queryClient = useQueryClient()
  const router = useRouter()
  return useMutation({
    mutationFn: () => api.post('/api/auth/logout'),
    onSettled: async () => {
      queryClient.clear()
      await router.invalidate()
      await router.navigate({ to: '/login', search: { redirect: undefined } })
    },
  })
}

function isActive(pathname: string, item: NavItem): boolean {
  if (item.exact) return pathname === item.to
  if (item.to === '/library') return pathname.startsWith('/library') || pathname.startsWith('/w/') || pathname.startsWith('/workflows/')
  return pathname === item.to || pathname.startsWith(item.to + '/')
}

function NewRecipeButton({ me, className, onNavigate }: { me: Me; className?: string; onNavigate?: () => void }) {
  if (canCreateInWorkspace(me.workspace?.role ?? null)) {
    return (
      <Link to="/workflows/new" onClick={onNavigate} className={buttonClass('brand', 'md', className)}>
        <Plus className="size-4" /> New recipe
      </Link>
    )
  }
  return (
    <Tip content="Viewers can run recipes but cannot create them" side="bottom">
      <Button variant="brand" disabled className={className} icon={<Plus className="size-4" />}>
        New recipe
      </Button>
    </Tip>
  )
}

function AiStatus({ model }: { model: Me['model'] }) {
  return (
    <div
      className="flex items-center gap-2.5 rounded-xl border border-sidebar-line bg-sidebar-2 px-3 py-2.5"
      title={
        model.available
          ? `Drafts are generated by ${model.model} (${model.provider}). Runs never use AI.`
          : 'No model key is configured. Manual editing and every saved recipe still work.'
      }
    >
      <Sparkles className={cn('size-4', model.available ? 'text-[#c4b1ff]' : 'text-sidebar-muted')} aria-hidden />
      <div className="min-w-0 flex-1">
        <div className="text-[12.5px] font-medium text-sidebar-ink">AI drafting</div>
        <div className="truncate text-[11px] text-sidebar-muted">
          {model.available ? model.model : 'Manual editing only'}
        </div>
      </div>
      <span
        className={cn(
          'inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold',
          model.available ? 'bg-[#3ccf78]/15 text-[#72e3a1]' : 'bg-white/8 text-sidebar-muted',
        )}
      >
        <span className={cn('size-1.5 rounded-full', model.available ? 'bg-[#3ccf78]' : 'bg-sidebar-muted')} />
        {model.available ? 'On' : 'Off'}
      </span>
    </div>
  )
}

/** After switching or creating a workspace: drop cached data and reload the session context. */
function useWorkspaceChanged() {
  const queryClient = useQueryClient()
  const router = useRouter()
  return async () => {
    queryClient.clear()
    await router.invalidate()
  }
}

function WorkspaceSwitcher({ me, onCreate, onNavigate }: { me: Me; onCreate: () => void; onNavigate?: () => void }) {
  const ws = me.workspace
  const changed = useWorkspaceChanged()
  const toast = useToast()
  const switchTo = useMutation({
    mutationFn: (workspaceId: string) => api.post<Me>('/api/me/workspace', { workspaceId }),
    onSuccess: async (next) => {
      await changed()
      onNavigate?.()
      toast.show({ tone: 'ok', title: `Now working in ${next.workspace?.workspaceName}`, description: 'The library, dashboard and Access page show this workspace.' })
    },
    onError: (err) => toast.show({ tone: 'bad', title: 'Could not switch workspace', description: err instanceof ApiError ? err.message : String(err) }),
  })

  const box = (
    <div className="flex items-center gap-2 rounded-xl border border-sidebar-line bg-sidebar-2 px-3 py-2.5 transition-colors hover:bg-white/[0.06]">
      <div className="min-w-0 flex-1">
        <div className="text-[11px] font-medium tracking-wide text-sidebar-muted uppercase">Workspace</div>
        <div className="mt-0.5 flex items-center gap-2">
          <span className="truncate text-sm font-semibold text-white">{ws ? ws.workspaceName : 'No workspace yet'}</span>
          {ws && (
            <Badge tone={ROLE_TONE[ws.role]} className="!bg-white/10 !text-sidebar-ink">
              {ws.role}
            </Badge>
          )}
        </div>
      </div>
      <ChevronsUpDown className="size-4 shrink-0 text-sidebar-muted" aria-hidden />
    </div>
  )

  return (
    <Menu label={ws ? `Workspace: ${ws.workspaceName}. Switch or create a workspace` : 'Create a workspace'} trigger={box}>
      {me.memberships.length > 0 && <MenuLabel>Your workspaces</MenuLabel>}
      {me.memberships.map((m) => (
        <MenuItem
          key={m.workspaceId}
          icon={<Building2 />}
          checked={m.workspaceId === ws?.workspaceId}
          hint={m.role}
          disabled={switchTo.isPending}
          onSelect={() => {
            if (m.workspaceId !== ws?.workspaceId) switchTo.mutate(m.workspaceId)
          }}
        >
          {m.workspaceName}
        </MenuItem>
      ))}
      {me.memberships.length > 0 && <MenuSeparator />}
      <MenuItem icon={<Plus />} onSelect={onCreate} hint="You'll be its admin">
        Create a workspace
      </MenuItem>
    </Menu>
  )
}

/** A new workspace with you as its admin; this browser switches to it. */
export function CreateWorkspaceDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [name, setName] = React.useState('')
  const [touched, setTouched] = React.useState(false)
  const changed = useWorkspaceChanged()
  const navigate = useNavigate()
  const toast = useToast()
  const create = useMutation({
    mutationFn: () => api.post<Me>('/api/workspaces', { name: name.trim() }),
    onSuccess: async (next) => {
      onClose()
      setName('')
      setTouched(false)
      await changed()
      await navigate({ to: '/' })
      toast.show({ tone: 'ok', title: `${next.workspace?.workspaceName} is ready`, description: 'Invite your team from the Access page.' })
    },
  })
  const problem = workspaceNameProblem(name)
  const error = create.error instanceof ApiError ? create.error.message : null
  return (
    <Dialog
      open={open}
      onClose={onClose}
      icon={<Building2 />}
      title="Create a workspace"
      description="A separate space for another team or client, with its own recipes and members. You'll be its admin."
      size="sm"
      footer={
        <>
          <Button variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button variant="brand" loading={create.isPending} disabled={!!problem} onClick={() => create.mutate()}>
            Create workspace
          </Button>
        </>
      }
    >
      <form
        onSubmit={(e) => {
          e.preventDefault()
          setTouched(true)
          if (!problem) create.mutate()
        }}
      >
        <Field label="Workspace name" htmlFor="new-workspace-name" error={touched && problem ? problem : undefined} hint="Your team, department or company">
          <Input id="new-workspace-name" value={name} maxLength={80} onChange={(e) => setName(e.target.value)} onBlur={() => setTouched(true)} placeholder="e.g. Finance team" />
        </Field>
      </form>
      {error && (
        <Callout tone="bad" className="mt-3">
          {error}
        </Callout>
      )}
    </Dialog>
  )
}

function SidebarContent({ me, onNavigate, onCreateWorkspace }: { me: Me; onNavigate?: () => void; onCreateWorkspace: () => void }) {
  const pathname = useRouterState({ select: (s) => s.location.pathname })
  const signOut = useSignOut()

  return (
    <div className="flex h-full flex-col gap-5 px-3.5 py-5">
      <Link to="/" onClick={onNavigate} className="px-2" aria-label="FlowPilot home">
        <Logo inverted />
      </Link>

      <WorkspaceSwitcher me={me} onCreate={onCreateWorkspace} onNavigate={onNavigate} />

      <NewRecipeButton me={me} onNavigate={onNavigate} className="w-full" />

      <nav className="flex flex-1 flex-col gap-5" aria-label="Main">
        {NAV.map((group) => (
          <div key={group.label}>
            <div className="px-2 pb-1.5 text-[11px] font-medium tracking-wide text-sidebar-muted uppercase">{group.label}</div>
            <ul className="space-y-0.5">
              {group.items.filter((item) => !item.adminOnly || me.workspace?.role === 'admin').map((item) => {
                const active = isActive(pathname, item)
                return (
                  <li key={item.to}>
                    <Link
                      to={item.to}
                      onClick={onNavigate}
                      aria-current={active ? 'page' : undefined}
                      className={cn(
                        'flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-[13.5px] font-medium transition-colors [&_svg]:size-4',
                        active
                          ? 'bg-white/10 text-white shadow-[inset_0_0_0_1px_rgb(255_255_255/0.06)]'
                          : 'text-sidebar-muted hover:bg-white/5 hover:text-sidebar-ink',
                      )}
                    >
                      {item.icon}
                      {item.label}
                    </Link>
                  </li>
                )
              })}
            </ul>
          </div>
        ))}
      </nav>

      <div className="space-y-2.5">
        <AiStatus model={me.model} />
        <div className="flex items-center gap-1 rounded-xl border border-sidebar-line bg-sidebar-2 p-1.5">
          <Link
            to="/account"
            onClick={onNavigate}
            aria-label="Account settings"
            className="flex min-w-0 flex-1 items-center gap-2.5 rounded-lg p-1 hover:bg-white/[0.06]"
          >
            <Avatar name={me.user.name} hue={me.user.hue} size={32} />
            <span className="min-w-0 flex-1">
              <span className="block truncate text-[13px] font-semibold text-white">{me.user.name}</span>
              <span className="block truncate text-[11.5px] text-sidebar-muted">{me.user.email}</span>
            </span>
          </Link>
          <button
            type="button"
            onClick={() => signOut.mutate()}
            disabled={signOut.isPending}
            className="grid size-8 place-items-center rounded-lg text-sidebar-muted hover:bg-white/10 hover:text-white"
            aria-label="Sign out"
            title="Sign out"
          >
            <LogOut className="size-4" />
          </button>
        </div>
      </div>
    </div>
  )
}

function ThemeToggle() {
  const [theme, toggle] = useTheme()
  return (
    <button
      type="button"
      onClick={toggle}
      className="grid size-9 shrink-0 place-items-center rounded-xl border border-line bg-surface text-muted shadow-soft hover:text-ink"
      aria-label={theme === 'dark' ? 'Switch to light theme' : 'Switch to dark theme'}
      title={theme === 'dark' ? 'Light theme' : 'Dark theme'}
    >
      {theme === 'dark' ? <Sun className="size-4" /> : <Moon className="size-4" />}
    </button>
  )
}

/** "⌘" on Apple platforms, "Ctrl" elsewhere (decided after hydration; SSR shows ⌘). */
function useModifierLabel(): string {
  const [label, setLabel] = React.useState('⌘')
  React.useEffect(() => {
    const platform = (navigator as Navigator & { userAgentData?: { platform?: string } }).userAgentData?.platform ?? navigator.platform ?? ''
    if (!/mac|iphone|ipad|ipod/i.test(platform || navigator.userAgent)) setLabel('Ctrl ')
  }, [])
  return label
}

export function AppShell({ me, children }: { me: Me; children: React.ReactNode }) {
  const modifier = useModifierLabel()
  const [drawerOpen, setDrawerOpen] = React.useState(false)
  const [paletteOpen, setPaletteOpen] = React.useState(false)
  const [createOpen, setCreateOpen] = React.useState(false)
  const pathname = useRouterState({ select: (s) => s.location.pathname })
  React.useEffect(() => setDrawerOpen(false), [pathname])

  React.useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault()
        setPaletteOpen((open) => !open)
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  const pages: PaletteLink[] = React.useMemo(
    () => [
      ...NAV.flatMap((g) => g.items.filter((i) => !i.adminOnly || me.workspace?.role === 'admin').map((i) => ({ label: i.label, to: i.to, icon: i.icon }))),
      ...(canCreateInWorkspace(me.workspace?.role ?? null)
        ? [{ label: 'New recipe', to: '/workflows/new', icon: <Plus />, hint: 'Describe a report and turn it into steps' }]
        : []),
      { label: 'Account settings', to: '/account', icon: <UserRound />, hint: 'Name, password and signed-in devices' },
    ],
    [me.workspace?.role],
  )

  return (
    <div className="min-h-dvh">
      <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 overflow-y-auto bg-sidebar lg:block">
        <SidebarContent me={me} onCreateWorkspace={() => setCreateOpen(true)} />
      </aside>

      {drawerOpen && (
        <div className="fixed inset-0 z-50 lg:hidden">
          <div className="animate-fade absolute inset-0 bg-black/50" onClick={() => setDrawerOpen(false)} aria-hidden />
          <aside className="animate-pop absolute inset-y-0 left-0 w-72 max-w-[85vw] overflow-y-auto bg-sidebar shadow-lift" aria-label="Menu">
            <button
              type="button"
              onClick={() => setDrawerOpen(false)}
              className="absolute top-4 right-3 grid size-8 place-items-center rounded-lg text-sidebar-muted hover:bg-white/10 hover:text-white"
              aria-label="Close menu"
            >
              <X className="size-4" />
            </button>
            <SidebarContent
              me={me}
              onNavigate={() => setDrawerOpen(false)}
              onCreateWorkspace={() => {
                setDrawerOpen(false)
                setCreateOpen(true)
              }}
            />
          </aside>
        </div>
      )}

      <div className="lg:pl-64">
        <header className="sticky top-0 z-20 border-b border-line bg-canvas/80 backdrop-blur-md">
          <div className="mx-auto flex h-15 max-w-[1320px] items-center gap-3 px-4 sm:px-6 lg:px-8">
            <button
              type="button"
              onClick={() => setDrawerOpen(true)}
              className="grid size-9 shrink-0 place-items-center rounded-xl border border-line bg-surface text-ink-2 lg:hidden"
              aria-label="Open menu"
            >
              <MenuIcon className="size-4" />
            </button>
            <button
              type="button"
              onClick={() => setPaletteOpen(true)}
              className="flex h-9 min-w-0 flex-1 items-center gap-2.5 rounded-xl border border-line bg-surface px-3 text-left text-[13.5px] text-faint shadow-soft transition-colors hover:border-line-strong sm:max-w-sm"
              aria-label="Search recipes and pages"
            >
              <Search className="size-4 shrink-0" aria-hidden />
              <span className="min-w-0 flex-1 truncate">Search recipes…</span>
              <span className="hidden sm:inline-flex">
                <Kbd>{modifier}K</Kbd>
              </span>
            </button>
            <div className="flex-1" />
            <ThemeToggle />
            <div className="hidden sm:block">
              <NewRecipeButton me={me} />
            </div>
          </div>
        </header>
        <main className="mx-auto max-w-[1320px] px-4 py-6 sm:px-6 sm:py-8 lg:px-8">{children}</main>
      </div>

      <CommandPalette open={paletteOpen} onClose={() => setPaletteOpen(false)} pages={pages} />
      <CreateWorkspaceDialog open={createOpen} onClose={() => setCreateOpen(false)} />
    </div>
  )
}
