/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppRunsRouteImport } from './routes/_app/runs'
import { Route as AppSystemDesignRouteImport } from './routes/_app/system-design'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as AppWorkflowsNewRouteImport } from './routes/_app/workflows.new'
import { Route as AppWWorkflowIdIndexRouteImport } from './routes/_app/w.$workflowId.index'
import { Route as AppWWorkflowIdEditRouteImport } from './routes/_app/w.$workflowId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemDesignRoute = AppSystemDesignRouteImport.update({
  id: '/system-design',
  path: '/system-design',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkflowIdIndexRoute = AppWWorkflowIdIndexRouteImport.update({
  id: '/w/$workflowId/',
  path: '/w/$workflowId/',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkflowIdEditRoute = AppWWorkflowIdEditRouteImport.update({
  id: '/w/$workflowId/edit',
  path: '/w/$workflowId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/library': typeof AppLibraryRoute
  '/runs': typeof AppRunsRoute
  '/system-design': typeof AppSystemDesignRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/w/$workflowId/edit': typeof AppWWorkflowIdEditRoute
  '/w/$workflowId/': typeof AppWWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/library': typeof AppLibraryRoute
  '/runs': typeof AppRunsRoute
  '/system-design': typeof AppSystemDesignRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/': typeof AppIndexRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/w/$workflowId/edit': typeof AppWWorkflowIdEditRoute
  '/w/$workflowId': typeof AppWWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/runs': typeof AppRunsRoute
  '/_app/system-design': typeof AppSystemDesignRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workflows/new': typeof AppWorkflowsNewRoute
  '/_app/w/$workflowId/edit': typeof AppWWorkflowIdEditRoute
  '/_app/w/$workflowId/': typeof AppWWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/welcome'
    | '/$'
    | '/access'
    | '/account'
    | '/audit'
    | '/library'
    | '/runs'
    | '/system-design'
    | '/api/$'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/workflows/new'
    | '/w/$workflowId/edit'
    | '/w/$workflowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/welcome'
    | '/$'
    | '/access'
    | '/account'
    | '/audit'
    | '/library'
    | '/runs'
    | '/system-design'
    | '/api/$'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/'
    | '/workflows/new'
    | '/w/$workflowId/edit'
    | '/w/$workflowId'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/welcome'
    | '/_app/$'
    | '/_app/access'
    | '/_app/account'
    | '/_app/audit'
    | '/_app/library'
    | '/_app/runs'
    | '/_app/system-design'
    | '/api/$'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/_app/'
    | '/_app/workflows/new'
    | '/_app/w/$workflowId/edit'
    | '/_app/w/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs': {
      id: '/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-design': {
      id: '/_app/system-design'
      path: '/system-design'
      fullPath: '/system-design'
      preLoaderRoute: typeof AppSystemDesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/new': {
      id: '/_app/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workflowId/': {
      id: '/_app/w/$workflowId/'
      path: '/w/$workflowId'
      fullPath: '/w/$workflowId/'
      preLoaderRoute: typeof AppWWorkflowIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workflowId/edit': {
      id: '/_app/w/$workflowId/edit'
      path: '/w/$workflowId/edit'
      fullPath: '/w/$workflowId/edit'
      preLoaderRoute: typeof AppWWorkflowIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccessRoute: typeof AppAccessRoute
  AppAccountRoute: typeof AppAccountRoute
  AppAuditRoute: typeof AppAuditRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppRunsRoute: typeof AppRunsRoute
  AppSystemDesignRoute: typeof AppSystemDesignRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AppWWorkflowIdEditRoute: typeof AppWWorkflowIdEditRoute
  AppWWorkflowIdIndexRoute: typeof AppWWorkflowIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccessRoute: AppAccessRoute,
  AppAccountRoute: AppAccountRoute,
  AppAuditRoute: AppAuditRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppRunsRoute: AppRunsRoute,
  AppSystemDesignRoute: AppSystemDesignRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AppWWorkflowIdEditRoute: AppWWorkflowIdEditRoute,
  AppWWorkflowIdIndexRoute: AppWWorkflowIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSplatRoute: ApiSplatRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
