/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppRunsRouteImport } from './routes/_app/runs'
import { Route as AppSystemDesignRouteImport } from './routes/_app/system-design'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppWorkflowsNewRouteImport } from './routes/_app/workflows.new'
import { Route as AppWWorkflowIdIndexRouteImport } from './routes/_app/w.$workflowId.index'
import { Route as AppWWorkflowIdEditRouteImport } from './routes/_app/w.$workflowId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemDesignRoute = AppSystemDesignRouteImport.update({
  id: '/system-design',
  path: '/system-design',
  getParentRoute: () => AppRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkflowIdIndexRoute = AppWWorkflowIdIndexRouteImport.update({
  id: '/w/$workflowId/',
  path: '/w/$workflowId/',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkflowIdEditRoute = AppWWorkflowIdEditRouteImport.update({
  id: '/w/$workflowId/edit',
  path: '/w/$workflowId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/library': typeof AppLibraryRoute
  '/runs': typeof AppRunsRoute
  '/system-design': typeof AppSystemDesignRoute
  '/api/$': typeof ApiSplatRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/w/$workflowId/edit': typeof AppWWorkflowIdEditRoute
  '/w/$workflowId/': typeof AppWWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/library': typeof AppLibraryRoute
  '/runs': typeof AppRunsRoute
  '/system-design': typeof AppSystemDesignRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AppIndexRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/w/$workflowId/edit': typeof AppWWorkflowIdEditRoute
  '/w/$workflowId': typeof AppWWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/runs': typeof AppRunsRoute
  '/_app/system-design': typeof AppSystemDesignRoute
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workflows/new': typeof AppWorkflowsNewRoute
  '/_app/w/$workflowId/edit': typeof AppWWorkflowIdEditRoute
  '/_app/w/$workflowId/': typeof AppWWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/access'
    | '/library'
    | '/runs'
    | '/system-design'
    | '/api/$'
    | '/workflows/new'
    | '/w/$workflowId/edit'
    | '/w/$workflowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/access'
    | '/library'
    | '/runs'
    | '/system-design'
    | '/api/$'
    | '/'
    | '/workflows/new'
    | '/w/$workflowId/edit'
    | '/w/$workflowId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/access'
    | '/_app/library'
    | '/_app/runs'
    | '/_app/system-design'
    | '/api/$'
    | '/_app/'
    | '/_app/workflows/new'
    | '/_app/w/$workflowId/edit'
    | '/_app/w/$workflowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs': {
      id: '/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system-design': {
      id: '/_app/system-design'
      path: '/system-design'
      fullPath: '/system-design'
      preLoaderRoute: typeof AppSystemDesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/new': {
      id: '/_app/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workflowId/': {
      id: '/_app/w/$workflowId/'
      path: '/w/$workflowId'
      fullPath: '/w/$workflowId/'
      preLoaderRoute: typeof AppWWorkflowIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workflowId/edit': {
      id: '/_app/w/$workflowId/edit'
      path: '/w/$workflowId/edit'
      fullPath: '/w/$workflowId/edit'
      preLoaderRoute: typeof AppWWorkflowIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccessRoute: typeof AppAccessRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppRunsRoute: typeof AppRunsRoute
  AppSystemDesignRoute: typeof AppSystemDesignRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AppWWorkflowIdEditRoute: typeof AppWWorkflowIdEditRoute
  AppWWorkflowIdIndexRoute: typeof AppWWorkflowIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccessRoute: AppAccessRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppRunsRoute: AppRunsRoute,
  AppSystemDesignRoute: AppSystemDesignRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AppWWorkflowIdEditRoute: AppWWorkflowIdEditRoute,
  AppWWorkflowIdIndexRoute: AppWWorkflowIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
